# vim:ft=kitty

# Include the Catppuccin Mocha Theme
include mocha.conf

# Set the font to a Nerd Font (for those rounded tmux icons!)
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0

# Add some nice breathing room around the edges
window_padding_width 10

# Hide the ugly top title bar to make it look clean
hide_window_decorations yes

# Cursor settings
cursor_shape block

# Override Catppuccin background with default Ubuntu Aubergine (Purple)
background #24273A

# Force X11 display server to disable Wayland smooth scrolling and restore old 'jumpy' scrolling
linux_display_server x11

# Reduce raw trackpad sensitivity at the terminal level 
touch_scroll_multiplier 0.05

# Unbind Kitty's default scrolling shortcuts so Neovim receives Ctrl+Shift+Up/Down
map ctrl+shift+up no_op
map ctrl+shift+down no_op
